Repository Codeit-Part4-SFJs/WDYTA, pull requests merged in 2024-05, with the labels that each got.

#5 feat: Primary, Secondary, Tertiary Button 생성
  package.json
  src/app/layout.tsx
  src/components/Compare/.keep
  src/components/Detail/.keep
  src/components/Login/.keep
  src/components/Main/.keep
  src/components/Profile/.keep
  src/components/Register/.keep
  src/components/SocialLogin/.keep
  src/shared/ui/Button/Button.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ feature, 💄 ui

#13 feat: Icon(Icon, Loading, Logo) 공통 컴포넌트 구현
  next.config.mjs
  package.json
  public/icon/add.svg
  public/icon/bubble.svg
  public/icon/category.svg
  public/icon/close.svg
  public/icon/drop-down.svg
  public/icon/drop-up.svg
  public/icon/google.svg
  public/icon/kakao.svg
  public/icon/kakaotalk.svg
  public/icon/loading.svg
  public/icon/logo.svg
  public/icon/menu.svg
  public/icon/my-profile.svg
  public/icon/photo.svg
  public/icon/save.svg
  public/icon/search.svg
  public/icon/share.svg
  public/icon/star.svg
  public/icon/unsave.svg
  public/icon/up-no-color.svg
  public/icon/up.svg
  public/icon/visibility-off.svg
  public/icon/visibility.svg
  src/app/Profile/page.tsx
  src/shared/ui/Icon/Icon.tsx
  src/shared/ui/Icon/Loading.tsx
  src/shared/ui/Icon/Logo.tsx
  svgr.d.ts
  tsconfig.json
  yarn.lock
Labels: ✨ feature, 💄 ui

#17 feat: Dropdown 컴포넌트 제작
  .eslintrc.json
  .storybook/main.ts
  eslint.config.cjs
  package.json
  src/shared/ui/Button/Button.stories.tsx
  src/shared/ui/Button/Button.tsx
  src/shared/ui/Dropdown/Dropdown.stories.tsx
  src/shared/ui/Dropdown/Dropdown.tsx
  src/shared/ui/Icon/Icon.tsx
  src/styles/globals.css
  tailwind.config.ts
  yarn.lock
Labels: 🆘 help wanted, ✨ feature, 🐞 bug, 💄 ui

#15 feat : 공통 input 컴포넌트 제작
  package.json
  src/shared/types/.keep
  src/shared/types/input.ts
  src/shared/ui/Input/.keep
  src/shared/ui/Input/AuthInput.tsx
  src/shared/ui/Input/ImageInput.tsx
  src/shared/ui/Input/TextBoxInput.tsx
  src/shared/ui/Input/TextFieldInput.tsx
  tailwind.config.ts
  yarn.lock
Labels: ✨ feature, 💄 ui

#18 feat: Chip 공통 컴포넌트 제작
  src/app/page.tsx
  src/shared/types/categoryChipType.ts
  src/shared/ui/Chip/.keep
  src/shared/ui/Chip/CategoryChip.tsx
  src/shared/ui/Chip/CategoryFilterChip.tsx
  src/shared/ui/Chip/CompareAChip.tsx
  src/shared/ui/Chip/CompareBChip.tsx
  src/shared/ui/Chip/RankingChip.tsx
  src/shared/ui/Chip/ThumbsChip.tsx
  src/styles/globals.css
Labels: ✨ feature, 💄 ui

#16 feat: SideMenu 공통 컴포넌트 제작
  .github/workflows/BuildTest.yml
  src/shared/ui/Menu/.keep
  src/shared/ui/Menu/SideMenu/SideMenu.tsx
  src/shared/ui/Menu/SideMenu/SideMenuTab.tsx
  src/shared/ui/Menu/SideMenu/api/getCategories.ts
  src/shared/ui/Menu/SideMenu/constant/DEFAULT_CATEGORIES.ts
  src/shared/ui/Menu/SideMenu/type/categoryType.ts
  src/store/slices/createCurrentCategorySlice.ts
  src/store/store.ts
  src/store/storeType.ts
  tailwind.config.ts
Labels: 💄 ui

#21 bug : tailwind css screens lg 속성 추가
  tailwind.config.ts
Labels: 🐞 bug

#28 feat: Discord 웹 훅 액션에 추가
  .github/workflows/NotificateMerged.yml
  .github/workflows/NotificatePullRequest.yml
Labels: ✨ feature

#30 refactor: Sidemenu 리팩토링 및 주스탄드 설정 수정
  src/shared/@common/hooks/useClose.ts
  src/shared/ui/Menu/SideMenu/SideMenu.tsx
  src/shared/ui/Menu/SideMenu/SideMenuOpenButton.tsx
  src/shared/ui/Menu/SideMenu/SideMenuTab.tsx
  src/shared/ui/Menu/SideMenu/api/getCategories.ts
  src/shared/ui/Menu/SideMenu/type/categoryType.ts
  src/store/slices/createCurrentCategorySlice.ts
  src/store/store.ts
  src/store/storeType.ts
  src/stores/storeType.ts
  src/stores/useExempleStore.ts
  src/stores/useSideMenuStore.ts
Labels: 🆘 help wanted, ✨ feature, 🛠 refactor

#35 refactor: Icon 공통 컴포넌트 리팩토링
  public/icon/add.svg
  public/icon/category.svg
  public/icon/close.svg
  public/icon/drop-down.svg
  public/icon/drop-up.svg
  public/icon/google.svg
  public/icon/kakao.svg
  public/icon/kakaotalk.svg
  public/icon/loading.svg
  public/icon/menu.svg
  public/icon/my-profile.svg
  public/icon/photo.svg
  public/icon/review.svg
  public/icon/save.svg
  public/icon/search.svg
  public/icon/share.svg
  public/icon/star.svg
  public/icon/unsave.svg
  public/icon/up-no-color.svg
  public/icon/visibility-off.svg
  public/icon/visibility.svg
  src/app/Profile/page.tsx
  src/shared/types/iconType.ts
  src/shared/ui/Chip/CategoryFilterChip.tsx
  src/shared/ui/Chip/CompareAChip.tsx
  src/shared/ui/Chip/CompareBChip.tsx
  src/shared/ui/Chip/ThumbsChip.tsx
  src/shared/ui/Dropdown/Dropdown.tsx
  src/shared/ui/Icon/Icon.tsx
  src/shared/ui/Icon/Loading.tsx
  src/shared/ui/Icon/Logo.tsx
  src/shared/ui/Input/AuthInput.tsx
  src/shared/ui/Input/ImageInput.tsx
Labels: 🛠 refactor

#31 feat & refactor : 공통 input 컴포넌트 리팩토링 및 storybook 작성
  src/shared/types/input.ts
  src/shared/ui/Input/AuthInput.tsx
  src/shared/ui/Input/Email/EmailInput.stories.tsx
  src/shared/ui/Input/Email/index.tsx
  src/shared/ui/Input/HelperText.tsx
  src/shared/ui/Input/Input.stories.tsx
  src/shared/ui/Input/Label.tsx
  src/shared/ui/Input/Nickname/NicknameInput.stories.tsx
  src/shared/ui/Input/Nickname/index.tsx
  src/shared/ui/Input/Password/PasswordInput.stories.tsx
  src/shared/ui/Input/Password/index.tsx
  src/shared/ui/Input/PasswordCheck/PasswordCheckInput.stories.tsx
  src/shared/ui/Input/PasswordCheck/index.tsx
  src/shared/ui/Input/TextBox/TextBoxInput.stories.tsx
  src/shared/ui/Input/TextBox/index.tsx
  src/shared/ui/Input/TextFieldInput.tsx
  src/shared/ui/Input/image/ImageInput.stories.tsx
  src/shared/ui/Input/image/index.tsx
  src/shared/ui/Input/index.tsx
Labels: ✨ feature, 📄 docs, 🛠 refactor

#38 feat: Icon 사용 시 color 추가
  src/shared/ui/Input/Password/index.tsx
  src/shared/ui/Input/PasswordCheck/index.tsx
  src/shared/ui/Input/image/index.tsx
Labels: ✨ feature

#46 refactor & docs: 공통 컴포넌트 Chip 리팩토링, Chip storybook 작성
  src/shared/ui/Chip/CategoryChip.tsx
  src/shared/ui/Chip/CategoryChip/CategoryChip.stories.tsx
  src/shared/ui/Chip/CategoryChip/index.tsx
  src/shared/ui/Chip/CategoryFilterChip/CategoryFilterChip.stories.tsx
  src/shared/ui/Chip/CategoryFilterChip/index.tsx
  src/shared/ui/Chip/CompareAChip.tsx
  src/shared/ui/Chip/CompareBChip.tsx
  src/shared/ui/Chip/CompareChip/CompareChip.stories.tsx
  src/shared/ui/Chip/CompareChip/index.tsx
  src/shared/ui/Chip/RankingChip.tsx
  src/shared/ui/Chip/RankingChip/RankingChip.stories.tsx
  src/shared/ui/Chip/RankingChip/index.tsx
  src/shared/ui/Chip/ThumbsChip.tsx
  src/shared/ui/Chip/ThumbsChip/ThumbsChip.stories.tsx
  src/shared/ui/Chip/ThumbsChip/index.tsx
  tailwind.config.ts
Labels: 📄 docs, 🛠 refactor, 💄 ui

#40 feat & refactor: Image 컴포넌트 스토리북 작성 및 리팩토링
  package.json
  src/shared/types/imageType.ts
  src/shared/ui/Img/ImageComponent.stories.tsx
  src/shared/ui/Img/ImageComponent.tsx
  yarn.lock
Labels: ✨ feature, 💄 ui

#42 feat & docs: Gnb 공통컴포넌트 제작 및 SideMenuOpenButton 수정 및 스토리북 추가
  src/app/compare/.keep
  src/app/detail/.keep
  src/app/layout.tsx
  src/app/login/.keep
  src/app/main/.keep
  src/app/profile/.keep
  src/app/register/.keep
  src/app/socialLogin/.keep
  src/shared/types/GnbType.ts
  src/shared/types/categoryType.ts
  src/shared/ui/Menu/Gnb/Gnb.stories.tsx
  src/shared/ui/Menu/Gnb/Gnb.tsx
  src/shared/ui/Menu/Gnb/GnbHamburgerMenu.tsx
  src/shared/ui/Menu/Gnb/GnbLogo.tsx
  src/shared/ui/Menu/Gnb/GnbSearch.tsx
  src/shared/ui/Menu/Gnb/GnbUser.tsx
  src/shared/ui/Menu/SideMenu/SideMenu.stories.tsx
  src/shared/ui/Menu/SideMenu/SideMenu.tsx
  src/shared/ui/Menu/SideMenu/SideMenuOpenButton.tsx
  src/shared/ui/Menu/SideMenu/SideMenuTab.tsx
  src/stores/storeType.ts
  src/stores/useExempleStore.ts
  src/stores/useSideMenuStore.ts
  src/styles/globals.css
Labels: ✨ feature, 📄 docs, 💄 ui

#48 feat : login 페이지 UI 작업
  src/app/Login/.keep
  src/app/Register/.keep
  src/app/login/.keep
  src/app/login/page.tsx
  src/components/Login/.keep
  src/components/Login/LoginForm.tsx
  src/components/Login/SocialLogin.tsx
  src/components/Register/.keep
  src/components/login/.keep
  src/components/register/.keep
  src/styles/globals.css
Labels: 💄 ui

#44 feat: Dropdown 추가 기능 구현, Floating, Sort 구현, Button 수정
  src/components/Login/LoginForm.tsx
  src/shared/ui/Button/Button/Button.stories.tsx
  src/shared/ui/Button/Button/index.tsx
  src/shared/ui/Button/Floating/Floating.stories.tsx
  src/shared/ui/Button/Floating/index.tsx
  src/shared/ui/Dropdown/Dropdown.tsx
  src/shared/ui/Dropdown/Dropdown/Dropdown.stories.tsx
  src/shared/ui/Dropdown/Dropdown/index.tsx
  src/shared/ui/Dropdown/Sort/Sort.stories.tsx
  src/shared/ui/Dropdown/Sort/index.tsx
Labels: ✨ feature, 🔨 fix, 🛠 refactor, 💄 ui

#53 hot fix: eslint 적용 및 폴더명 대소문자 및 index.ts 파일 추가
  .eslintrc.json
  .prettierrc
  eslint.config.cjs
  package.json
  src/app/Compare/.keep
  src/app/Detail/.keep
  src/app/Main/.keep
  src/app/Profile/.keep
  src/app/SocialLogin/.keep
  src/app/compare/.keep
  src/app/detail/.keep
  src/app/login/page.tsx
  src/app/main/.keep
  src/app/profile/.keep
  src/app/register/.keep
  src/app/socialLogin/.keep
  src/components/Login/LoginForm.tsx
  src/components/compare/.keep
  src/components/detail/.keep
  src/components/main/.keep
  src/components/profile/.keep
  src/components/socialLogin/.keep
  src/shared/@common/.keep
  src/shared/ui/Button/.keep
  src/shared/ui/Dropdown/.keep
  yarn.lock
Labels: 🔥 hot fix!!

#51 feat : 회원가입 페이지 UI 작업
  src/app/register/.keep
  src/app/register/page.tsx
  src/components/Register/RegisterForm.tsx
Labels: 💄 ui

#52 feat: 간편 회원가입 페이지 UI 작업
  src/app/SocialLogin/.keep
  src/app/socialLogin/page.tsx
  src/components/SocialLogin/SosialLoginForm.tsx
Labels: 💄 ui

#57 feat: compare 기초 구현, index.ts 수정, floating 수정
  package.json
  src/app/compare/page.tsx
  src/app/layout.tsx
  src/app/socialLogin/.keep
  src/components/Compare/.keep
  src/components/Detail/.keep
  src/components/Login/LoginForm.tsx
  src/components/Main/.keep
  src/components/Profile/.keep
  src/components/Register/RegisterForm.tsx
  src/components/SocialLogin/.keep
  src/components/SocialLogin/SosialLoginForm.tsx
  src/shared/types/GnbType.ts
  src/shared/types/categoryChipType.ts
  src/shared/ui/Button/Button/Button.stories.tsx
  src/shared/ui/Button/Button/Button.tsx
  src/shared/ui/Button/Button/index.ts
  src/shared/ui/Button/Floating/Floating.stories.tsx
  src/shared/ui/Button/Floating/Floating.tsx
  src/shared/ui/Button/Floating/index.ts
  src/shared/ui/Button/Floating/index.tsx
  src/shared/ui/Chip/CategoryChip/CategoryChip.stories.tsx
  src/shared/ui/Chip/CategoryChip/index.tsx
  src/shared/ui/Chip/CategoryFilterChip/CategoryFilterChip.stories.tsx
  src/shared/ui/Chip/CategoryFilterChip/index.tsx
  src/shared/ui/Dropdown/Dropdown/Dropdown.stories.tsx
  src/shared/ui/Dropdown/Dropdown/Dropdown.tsx
  src/shared/ui/Dropdown/Dropdown/index.ts
  src/shared/ui/Dropdown/Sort/Sort.stories.tsx
  src/shared/ui/Dropdown/Sort/Sort.tsx
  src/shared/ui/Dropdown/Sort/index.ts
  src/shared/ui/Input/Input.tsx
  yarn.lock
Labels: 🔥 hot fix!!, 🛠 refactor, 💄 ui

#60 refactor : index.ts 및 import 수정
  package.json
  src/app/Compare/.keep
  src/app/socialLogin/page.tsx
  src/components/Login/LoginForm.tsx
  src/components/Register/RegisterForm.tsx
  src/components/SocialLogin/SocialLoginForm.tsx
  src/shared/ui/Input/Email/EmailInput.stories.tsx
  src/shared/ui/Input/Email/EmailInput.tsx
  src/shared/ui/Input/Email/index.ts
  src/shared/ui/Input/Input.stories.tsx
  src/shared/ui/Input/Input.tsx
  src/shared/ui/Input/Nickname/NicknameInput.stories.tsx
  src/shared/ui/Input/Nickname/NicknameInput.tsx
  src/shared/ui/Input/Nickname/index.ts
  src/shared/ui/Input/Password/PasswordInput.stories.tsx
  src/shared/ui/Input/Password/PasswordInput.tsx
  src/shared/ui/Input/Password/index.ts
  src/shared/ui/Input/PasswordCheck/PasswordCheckInput.stories.tsx
  src/shared/ui/Input/PasswordCheck/PasswordCheckInput.tsx
  src/shared/ui/Input/PasswordCheck/index.ts
  src/shared/ui/Input/TextBox/TextBoxInput.stories.tsx
  src/shared/ui/Input/TextBox/TextBoxInput.tsx
  src/shared/ui/Input/TextBox/index.ts
  src/shared/ui/Input/image/ImageInput.stories.tsx
  src/shared/ui/Input/image/ImageInput.tsx
  src/shared/ui/Input/image/index.ts
  src/shared/ui/Input/index.ts
Labels: 🛠 refactor

#62 refactor: index 모듈화 및 경로수정
  src/app/layout.tsx
  src/shared/@common/hooks/index.ts
  src/shared/@common/hooks/useClose.ts
  src/shared/ui/Dropdown/Dropdown/Dropdown.tsx
  src/shared/ui/Dropdown/Sort/Sort.tsx
  src/shared/ui/Menu/Gnb/Gnb.stories.tsx
  src/shared/ui/Menu/Gnb/Gnb.tsx
  src/shared/ui/Menu/Gnb/GnbHamburgerMenu.tsx
  src/shared/ui/Menu/Gnb/GnbLogo.tsx
  src/shared/ui/Menu/Gnb/GnbSearch.tsx
  src/shared/ui/Menu/Gnb/GnbUser.tsx
  src/shared/ui/Menu/Gnb/index.ts
  src/shared/ui/Menu/Gnb/types/gnbType.ts
  src/shared/ui/Menu/SideMenu/SideMenu.stories.tsx
  src/shared/ui/Menu/SideMenu/SideMenu.tsx
  src/shared/ui/Menu/SideMenu/SideMenuOpenButton.tsx
  src/shared/ui/Menu/SideMenu/SideMenuTab.tsx
  src/shared/ui/Menu/SideMenu/constant/DEFAULT_CATEGORIES.ts
  src/shared/ui/Menu/SideMenu/index.ts
  src/shared/ui/Menu/SideMenu/types/categoryType.ts
  src/stores/index.ts
  src/stores/useExampleStore.ts
  src/stores/useSideMenuStore.ts
  yarn.lock
Labels: 🔥 hot fix!!, 🛠 refactor

#63 refactor: index.ts 모듈화 및 수정된 경로 반영
  src/app/compare/.keep
  src/app/compare/page.tsx
  src/components/Login/SocialLogin.tsx
  src/shared/ui/Button/Floating/Floating.tsx
  src/shared/ui/Chip/CategoryFilterChip/index.tsx
  src/shared/ui/Chip/CompareChip/index.tsx
  src/shared/ui/Chip/ThumbsChip/index.tsx
  src/shared/ui/Dropdown/Dropdown/Dropdown.tsx
  src/shared/ui/Dropdown/Sort/Sort.tsx
  src/shared/ui/Icon/Icon.stories.tsx
  src/shared/ui/Icon/Icon.tsx
  src/shared/ui/Icon/Loading.stories.tsx
  src/shared/ui/Icon/Loading.tsx
  src/shared/ui/Icon/Logo.stories.tsx
  src/shared/ui/Icon/Logo.tsx
  src/shared/ui/Icon/index.ts
  src/shared/ui/Icon/type/iconType.ts
  src/shared/ui/Icon/types/iconType.ts
  src/shared/ui/Img/ImageComponent.stories.tsx
  src/shared/ui/Img/ImageComponent.tsx
  src/shared/ui/Img/index.ts
  src/shared/ui/Img/types/imageType.ts
  src/shared/ui/Input/Password/PasswordInput.tsx
  src/shared/ui/Input/PasswordCheck/PasswordCheckInput.tsx
  src/shared/ui/Input/image/ImageInput.tsx
  src/shared/ui/Menu/Gnb/GnbHamburgerMenu.tsx
  src/shared/ui/Menu/Gnb/GnbLogo.tsx
  src/shared/ui/Menu/Gnb/GnbSearch.tsx
Labels: 🛠 refactor

#64 refactor: index 파일 설정 및 병합 충돌 해결 및 공통 폴더 추가
  .eslintrc.json
  src/components/Login/LoginForm.tsx
  src/components/Register/RegisterForm.tsx
  src/components/SocialLogin/SocialLoginForm.tsx
  src/shared/@common/apis/.keep
  src/shared/@common/types/input.ts
  src/shared/@common/utils/.keep
  src/shared/ui/Chip/CategoryChip/CategoryChip.stories.tsx
  src/shared/ui/Chip/CategoryChip/CategoryChip.tsx
  src/shared/ui/Chip/CategoryChip/index.ts
  src/shared/ui/Chip/CategoryFilterChip/CategoryFilterChip.stories.tsx
  src/shared/ui/Chip/CategoryFilterChip/CategoryFilterChip.tsx
  src/shared/ui/Chip/CategoryFilterChip/index.ts
  src/shared/ui/Chip/CompareChip/CompareChip.stories.tsx
  src/shared/ui/Chip/CompareChip/CompareChip.tsx
  src/shared/ui/Chip/CompareChip/index.ts
  src/shared/ui/Chip/RankingChip/RankingChip.stories.tsx
  src/shared/ui/Chip/RankingChip/RankingChip.tsx
  src/shared/ui/Chip/RankingChip/index.ts
  src/shared/ui/Chip/ThumbsChip/ThumbsChip.stories.tsx
  src/shared/ui/Chip/ThumbsChip/ThumbsChip.tsx
  src/shared/ui/Chip/ThumbsChip/index.ts
  src/shared/ui/Chip/types/categoryChipType.ts
  src/shared/ui/Dropdown/Dropdown/Dropdown.tsx
  src/shared/ui/Img/types/imageType.ts
  src/shared/ui/Input/Email/EmailInput.stories.tsx
  src/shared/ui/Input/Email/EmailInput.tsx
  src/shared/ui/Input/Nickname/NicknameInput.stories.tsx
  src/shared/ui/Input/Nickname/NicknameInput.tsx
  src/shared/ui/Input/Password/PasswordInput.stories.tsx
  src/shared/ui/Input/Password/PasswordInput.tsx
  src/shared/ui/Input/PasswordCheck/PasswordCheckInput.stories.tsx
  src/shared/ui/Input/PasswordCheck/PasswordCheckInput.tsx
  src/shared/ui/Input/TextBox/TextBoxInput.stories.tsx
  src/shared/ui/Input/TextBox/TextBoxInput.tsx
  src/shared/ui/Menu/SideMenu/SideMenuOpenButton.tsx
Labels: 🔥 hot fix!!

#70 common: 공통 API 및 auth 파일 삭제
  src/shared/@common/apis/.keep
  src/shared/@common/apis/constants/API.ts
  src/shared/auth/.keep
  src/shared/auth/hooks/.keep
Labels: ⚙ api

#71 chore: Pretendard 폰트 적용
  src/app/layout.tsx
  src/fonts/PretendardVariable.woff2
  src/styles/globals.css
Labels: 💄 ui

#73 feat: Oauth, Image, Auth API 세팅
  src/shared/@common/apis/auth.ts
  src/shared/@common/apis/image.ts
  src/shared/@common/apis/oauth.ts
Labels: ⚙ api
