Repository Codeit-Part4-SFJs/WDYTA, pull requests merged in 2024-06, with the labels that each got.

#80 로그인 페이지 API 연동 및 기능 구현
  src/components/Login/LoginForm.tsx
  src/components/Login/hooks/useLoginMutation.ts
  src/components/Login/loginAction.ts
  src/components/Register/RegisterForm.tsx
  tailwind.config.ts
Labels: ✨ feature, ⚙ api

#78 feat: 상품 상세 페이지 UI 및 스켈레톤 UI 구현 완료, Gnb,SideMenu 리팩토링, 공용 API 추가
  src/app/Detail/.keep
  src/app/[category]/[product]/layout.tsx
  src/app/[category]/[product]/page.tsx
  src/app/[category]/page.tsx
  src/app/detail/.keep
  src/components/Detail/MainSectionLayout/MainSectionLayout.tsx
  src/components/Detail/MainSectionLayout/index.ts
  src/components/Detail/ProductDetail/DetailFavoriteButton.tsx
  src/components/Detail/ProductDetail/ProductDetail.tsx
  src/components/Detail/ProductDetail/ShareButtons.tsx
  src/components/Detail/ProductDetail/index.ts
  src/components/Detail/ProductReviews/ProductReviews.tsx
  src/components/Detail/ProductReviews/ReviewImage.tsx
  src/components/Detail/ProductReviews/ReviewLikeButton.tsx
  src/components/Detail/ProductReviews/ReviewProfile.tsx
  src/components/Detail/ProductReviews/index.ts
  src/components/Detail/ProductStatistics/ProductStatistics.tsx
  src/components/Detail/ProductStatistics/index.ts
  src/components/Detail/constants/SORT_OPTIONS.ts
  src/components/Detail/constants/STATISTICS_OPTIONS.ts
  src/components/Detail/constants/index.ts
  src/components/Detail/mock/DETAIL_MOCK.ts
  src/components/Detail/mock/PRODUCT_MOCK.ts
  src/components/Detail/mock/REVIEWS_MOCK.ts
  src/components/Detail/mock/index.ts
  src/components/Detail/skeletons/SkeletonProductDetail.tsx
  src/components/Detail/skeletons/SkeletonProductReviews.tsx
  src/components/Detail/skeletons/SkeletonProductStatistics.tsx
  src/components/Detail/skeletons/index.ts
  src/components/Detail/types/ProductReviewsType.ts
  src/components/Detail/types/ProductStatisticsType.ts
  src/components/Detail/types/index.ts
  src/shared/@common/apis/category.ts
  src/shared/@common/apis/index.ts
  src/shared/@common/apis/review.ts
  src/shared/@common/apis/user.ts
  src/shared/@common/utils/.keep
  src/shared/@common/utils/convertCategoryToId.ts
  src/shared/@common/utils/convertCreatedAt.ts
  src/shared/@common/utils/convertIdToCategory.ts
  src/shared/@common/utils/index.ts
  src/shared/ui/Button/Button/Button.tsx
  src/shared/ui/Button/Floating/Floating.tsx
  src/shared/ui/Dropdown/Sort/Sort.tsx
  src/shared/ui/Img/ImageComponent.tsx
  src/shared/ui/Img/types/imageType.ts
  src/shared/ui/Menu/Gnb/GnbHamburgerMenu.tsx
  src/shared/ui/Menu/Gnb/GnbSearch.tsx
  src/shared/ui/Menu/Gnb/GnbSettingButton.tsx
  src/shared/ui/Menu/Gnb/GnbUser.tsx
  src/shared/ui/Menu/SideMenu/SideMenu.tsx
  src/shared/ui/Menu/SideMenu/SideMenuOpenButton.tsx
  src/shared/ui/Menu/SideMenu/SideMenuTab.tsx
  src/shared/ui/Menu/SideMenu/constants/DEFAULT_CATEGORIES.ts
  src/shared/ui/Menu/SideMenu/types/categoryType.ts
  src/stores/storeType.ts
  src/stores/useSideMenuStore.ts
  yarn.lock
Labels: ✨ feature, ⚙ api, 💄 ui

#83 api: 로그인 상태에 따른 GnB 분기 처리
  src/app/[category]/[product]/page.tsx
  src/middleware.ts
  src/shared/ui/Menu/Gnb/Gnb.tsx
  src/shared/ui/Menu/Gnb/GnbHamburgerMenu.tsx
  src/shared/ui/Menu/Gnb/GnbSettingButton.tsx
  src/shared/ui/Menu/Gnb/GnbUser.tsx
  src/shared/ui/Menu/Gnb/types/gnbType.ts
Labels: ⚙ api

#86 feat: 로그아웃 action 기능 구현
  src/components/Login/loginAction.ts
  src/shared/@common/utils/index.ts
  src/shared/@common/utils/logoutAction.ts
  src/shared/ui/Menu/Gnb/GnbSettingButton.tsx
Labels: ✨ feature

#81 feat: 프로필 페이지 ui 구현
  src/app/Profile/.keep
  src/app/profile/.keep
  src/app/profile/[userId]/page.tsx
  src/app/profile/page.tsx
  src/components/@common/ProductCard.tsx
  src/components/Profile/ActivityCard.tsx
  src/components/Profile/ActivitySection.tsx
  src/components/Profile/ProductSection.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/ProfilePageComponent.tsx
  src/components/Profile/index.ts
  src/shared/@common/apis/follow.ts
  src/shared/@common/apis/product.ts
  src/shared/ui/Img/ImageComponent.tsx
Labels: ✨ feature, ⚙ api, 💄 ui

#87 fix: follow, product api 세팅 수정
  src/shared/@common/apis/follow.ts
  src/shared/@common/apis/product.ts
Labels: ⚙ api, 🐞 bug

#89 api: Tanstack Query 초기 설정
  package.json
  src/app/clientProviders.tsx
  src/app/getQueryClient.ts
  src/app/layout.tsx
  src/app/providers.tsx
  yarn.lock
Labels: ⚙ api

#94 api: 상품 상세 페이지의 상품 소개, 통계 컴포넌트 API 연동
  src/app/[category]/[product]/page.tsx
  src/app/[category]/[product]/queryKeyFactories.ts
  src/app/[category]/[product]/queryOptions.ts
  src/app/not-found.tsx
  src/components/Detail/ProductDetail/DetailFavoriteButton.tsx
  src/components/Detail/ProductDetail/ProductDetail.tsx
  src/components/Detail/ProductStatistics/ProductStatistics.tsx
  src/components/Detail/skeletons/SkeletonProductStatistics.tsx
  src/components/Detail/types/index.ts
  src/components/Detail/types/productDetailType.ts
  src/components/Detail/types/productReviewsType.ts
  src/components/Detail/types/productStatisticsType.ts
  src/shared/@common/apis/product.ts
  src/shared/ui/Menu/Gnb/GnbHamburgerMenu.tsx
Labels: ⚙ api

#99 feat: 카카오톡 소셜 로그인 구현
  src/app/oauth/page.tsx
  src/app/oauth/register/page.tsx
  src/app/socialLogin/page.tsx
  src/components/Login/SocialLogin.tsx
  src/components/Oauth/SocialLoginForm.tsx
  src/components/Oauth/hooks/useSignInMutation.ts
  src/components/Oauth/hooks/useSignUpMutation.ts
  src/shared/@common/apis/auth.ts
Labels: ✨ feature

#100 refactor: 상품 상세 페이지 리팩토링
  src/app/[category]/[product]/queryOptions.ts
  src/components/Detail/ProductDetail/DetailFavoriteButton.tsx
  src/components/Detail/ProductDetail/FavoriteButton.tsx
  src/components/Detail/ProductDetail/ProductDetail.tsx
  src/components/Detail/ProductDetail/hooks/index.ts
  src/components/Detail/ProductDetail/hooks/useFavoriteMutation.ts
  src/components/Detail/ProductReviews/ControlButtons.tsx
  src/components/Detail/ProductReviews/LikeButton.tsx
  src/components/Detail/ProductReviews/ProductReviews.tsx
  src/components/Detail/ProductReviews/ReviewCard.tsx
  src/components/Detail/ProductReviews/ReviewProfile.tsx
  src/components/Detail/ProductReviews/hooks/index.ts
  src/components/Detail/ProductReviews/hooks/useDeleteReviewMutation.ts
  src/components/Detail/ProductReviews/hooks/useLikeMutation.ts
  src/components/Detail/ProductStatistics/ProductStatistics.tsx
  src/components/Detail/ProductStatistics/Statistic.tsx
  src/components/Detail/types/productDetailType.ts
  src/components/Detail/types/productReviewsType.ts
  src/shared/@common/apis/product.ts
Labels: 🛠 refactor

#105 feat: 로그인 관련 로딩, 에러 처리 구현
  src/app/oauth/page.tsx
  src/components/Login/SocialLogin.tsx
  src/components/Oauth/hooks/useSignInMutation.ts
  src/shared/ui/Icon/Loading.tsx
Labels: ✨ feature, 💄 ui

#108 상품 리뷰 모달, 상품 편집 모달 UI 작업
  src/components/Detail/ProductDetail/modal/EditModal.tsx
  src/components/Detail/ProductDetail/modal/ReviewModal.tsx
  src/components/Detail/ProductDetail/modal/index.ts
  src/shared/ui/Input/TextBox/TextBoxInput.stories.tsx
  src/shared/ui/Input/TextBox/TextBoxInput.tsx
  src/shared/ui/Input/image/ImageInput.tsx
Labels: 💄 ui

#109 feat: 홈페이지 UI 구현 및 리팩토링, skeleton, API 초기 세팅
  src/app/[category]/homeQueryKeyFactories.ts
  src/app/page.tsx
  src/components/Home/MainProducts/MainProducts.tsx
  src/components/Home/RankingCard/RankingCard.tsx
  src/components/Home/ReviewerRanking/ReviewerRanking.tsx
  src/components/Home/constants/HOME_SORT_OPTIONS.ts
  src/components/Home/mock/CATEGORY_LIST_MOCK.ts
  src/components/Home/mock/HOME_PRODUCT_LIST_MOCK.ts
  src/components/Home/mock/RANKING_LIST_MOCK.ts
  src/components/Home/skeletons/SkeletonMainCard.tsx
  src/components/Home/skeletons/SkeletonMainProducts.tsx
  src/components/Home/skeletons/SkeletonMainTitle.tsx
  src/components/Home/skeletons/SkeletonRankingCard.tsx
  src/components/Home/skeletons/SkeletonRankingTitle.tsx
  src/components/Home/skeletons/SkeletonReviewerRanking.tsx
  src/components/Home/types/ProductType.ts
  src/components/Home/types/RankingType.ts
  src/shared/@common/apis/constants/API.ts
  src/shared/@common/apis/product.ts
  src/shared/@common/utils/adaptRanking.ts
  src/shared/ui/Button/Floating/Floating.tsx
  src/shared/ui/Chip/RankingChip/RankingChip.stories.tsx
  src/shared/ui/Chip/RankingChip/RankingChip.tsx
Labels: ⚙ api, 🛠 refactor, 💄 ui

#111 feat: AlertModal UI 구현
  src/components/@common/AlertModal.tsx
Labels: 💄 ui

#114 feat: Modal 초기 세팅
  src/app/@modal/(.)modal/example1/page.tsx
  src/app/@modal/(.)modal/example2/page.tsx
  src/app/@modal/default.ts
  src/app/layout.tsx
  src/app/modal/example1/page.tsx
  src/app/modal/example2/page.tsx
  src/components/@common/modal/AlertModal.tsx
  src/components/@common/modal/index.ts
  src/components/Detail/modal/EditModal.tsx
  src/components/Detail/modal/ReviewModal.tsx
  src/components/Detail/modal/index.ts
  src/shared/@common/hooks/index.ts
  src/shared/@common/hooks/useCloseModal.ts
  src/shared/ui/Modal/Modal.tsx
  src/shared/ui/Modal/index.ts
Labels: ✨ feature

#118 모달 초기 UI 작업
  src/app/@modal/(.)modal/example1/page.tsx
  src/app/@modal/(.)modal/example2/page.tsx
  src/app/modal/example1/page.tsx
  src/app/modal/example2/page.tsx
  src/shared/ui/Modal/Modal.tsx
Labels: 💄 ui

#116 feat: 프로필 페이지 스켈레톤 구현
  src/app/profile/page.tsx
  src/components/Profile/ActivitySection/ActivityCard.tsx
  src/components/Profile/skeleton/SkeletonActivitySection.tsx
  src/components/Profile/skeleton/SkeletonProductSection.tsx
  src/components/Profile/skeleton/SkeletonProfileCard.tsx
Labels: 💄 ui

#122 feat: AlertModal 연결
  src/app/@modal/(.)modal/example2/page.tsx
  src/app/@modal/(.)modal/login/page.tsx
  src/app/@modal/(.)modal/oauth/page.tsx
  src/app/@modal/(.)modal/oauth/register/page.tsx
  src/app/@modal/(.)modal/register/page.tsx
  src/app/modal/example2/page.tsx
  src/app/modal/login/page.tsx
  src/app/modal/oauth/page.tsx
  src/app/modal/oauth/register/page.tsx
  src/app/modal/register/page.tsx
  src/components/@common/modal/AlertModal.tsx
  src/components/Detail/ProductReviews/ReviewCard.tsx
  src/components/Login/hooks/useLoginMutation.ts
  src/components/Oauth/hooks/useSignInMutation.ts
  src/components/Oauth/hooks/useSignUpMutation.ts
  src/components/Register/RegisterForm.tsx
  src/components/Register/hooks/useRegisterMutation.ts
Labels: ✨ feature

#91 feat: compare 페이지 구현
  .eslintrc.json
  src/app/compare/compareQueryKeyFactories.ts
  src/app/compare/page.tsx
  src/app/compare/queryOptions.ts
  src/components/Compare/AutoComplete.tsx
  src/components/Compare/ComparingButton.tsx
  src/components/Compare/Table.tsx
  src/components/Compare/hooks/ComparisonResult.tsx
  src/components/Compare/mock/PRODUCT_ID_1_MOCK.ts
  src/components/Compare/mock/PRODUCT_ID_2_MOCK.ts
  src/components/Compare/mock/PRODUCT_LIST_MOCK.ts
  src/components/Compare/mock/index.ts
  src/components/Compare/types/index.ts
  src/components/Compare/types/productDetailType.ts
  src/components/Detail/modal/EditModal.tsx
  src/shared/@common/apis/product.ts
  src/shared/ui/Dropdown/Dropdown/Dropdown.tsx
  src/shared/ui/Input/Input.tsx
  src/stores/useCompareItems.ts
Labels: 🆘 help wanted, ✨ feature, ⚙ api

#125 feat : 이미지 Input 수정
  src/components/@common/modal/ProductModal.tsx
  src/components/@common/modal/index.ts
  src/components/Detail/modal/ReviewModal.tsx
  src/components/Detail/modal/index.ts
  src/shared/@common/apis/image.ts
  src/shared/@common/hooks/index.ts
  src/shared/@common/hooks/useImageMutation.ts
  src/shared/@common/utils/changeImage.ts
  src/shared/@common/utils/index.ts
  src/shared/ui/Input/image/ImageInput.stories.tsx
  src/shared/ui/Input/image/ImageInput.tsx
Labels: ✨ feature, 🛠 refactor

#130 fix: 빌드 오류 해결 및 랭킹카드 Link태그 경로 수정
  src/components/@common/ProductCard.tsx
  src/components/Home/RankingCard/RankingCard.tsx
  src/shared/@common/apis/product.ts
Labels: 🔨 fix, 🔥 hot fix!!

#131 feat: 상품 리뷰 모달 구현
  src/app/@modal/(.)modal/detail/review/page.tsx
  src/app/[category]/[product]/page.tsx
  src/app/modal/detail/review/page.tsx
  src/components/Detail/ProductDetail/ProductDetail.tsx
  src/components/Detail/ProductReviews/hooks/useCreateReviewMutation.tsx
  src/components/Detail/modal/ReviewModal.tsx
  src/components/Detail/types/productDetailType.ts
  src/shared/@common/apis/review.ts
Labels: ✨ feature

#134 feat: CICD 자동화 구축
  .env.production
  .eslintrc.json
  .github/workflows/CICD.yml
  Dockerfile
  next.config.mjs
Labels: ✨ feature

#138 feat: yml build 액션 추가
  .github/workflows/CICD.yml
Labels: ✨ feature

#147 feat: 상품 추가 모달 구현
  src/app/@modal/(.)modal/home/productAdd/page.tsx
  src/app/modal/home/productAdd/page.tsx
  src/components/@common/modal/ProductModal.tsx
  src/components/@common/modal/constants/CATEGORY_DROPDOWN_OPTIONS.ts
  src/components/Home/RankingCard/RankingCard.tsx
  src/components/Home/hooks/useProductAddMutation.ts
  src/shared/@common/apis/product.ts
  src/shared/@common/types/input.ts
  src/shared/ui/Button/Floating/Floating.tsx
Labels: ✨ feature, ⚙ api

#150 #149 feat: ProductInput 구현
  src/shared/ui/Input/product/ProductInput.tsx
  src/shared/ui/Input/product/index.ts
Labels: ✨ feature

#148 feat: 비교 상품 교체 모달 구현
  src/app/@modal/(.)modal/compare/check/page.tsx
  src/app/@modal/(.)modal/compare/duplicate/page.tsx
  src/app/@modal/(.)modal/compare/page.tsx
  src/app/compare/page.tsx
  src/app/modal/compare/check/page.tsx
  src/app/modal/compare/duplicate/page.tsx
  src/app/modal/compare/page.tsx
  src/components/@common/modal/AlertModal.tsx
  src/components/@common/modal/CheckModal.tsx
  src/components/@common/modal/CompareModal.tsx
  src/components/Compare/AutoComplete.tsx
  src/components/Compare/ComparingButton.tsx
  src/components/Compare/ComparisonResult.tsx
  src/components/Compare/Table.tsx
  src/components/Compare/index.ts
  src/components/Compare/skeletons/SkeletonCompare.tsx
  src/components/Detail/ProductDetail/ProductDetail.tsx
  src/shared/ui/Button/Button/Button.tsx
  src/shared/ui/Menu/Gnb/GnbCompareButton.tsx
  src/shared/ui/Menu/Gnb/GnbUser.tsx
  src/shared/ui/Menu/Gnb/index.ts
Labels: ✨ feature, ⚙ api, 💄 ui

#151 feat : 상품 편집 모달 구현
  src/app/@modal/(.)modal/detail/edit/page.tsx
  src/app/modal/detail/edit/page.tsx
  src/components/@common/modal/constants/CATEGORY_DROPDOWN_OPTIONS.ts
  src/components/Detail/ProductDetail/ProductDetail.tsx
  src/components/Detail/ProductDetail/hooks/index.ts
  src/components/Detail/ProductDetail/hooks/useEditProductMutation.ts
  src/components/Detail/modal/EditModal.tsx
  src/components/Detail/modal/index.ts
Labels: ✨ feature

#153 bug: login, register alertModal path 삭제
  src/app/@modal/(.)modal/example1/page.tsx
  src/app/@modal/(.)modal/login/page.tsx
  src/app/@modal/(.)modal/register/page.tsx
  src/app/modal/example1/page.tsx
  src/app/modal/login/page.tsx
  src/app/modal/register/page.tsx
Labels: 🐞 bug

#155 feat : 이미지 Input 확장자 제한하기
  src/components/Detail/modal/ReviewModal.tsx
  src/shared/@common/utils/changeImage.ts
  src/shared/@common/utils/constants/Image.ts
Labels: ✨ feature

#158 UI: 404 페이지 UI
  public/404.gif
  src/app/not-found.tsx
Labels: 💄 ui

#162 fix: Modal 수정
  src/app/modal/compare/page.tsx
  src/components/@common/modal/CheckModal.tsx
  src/components/@common/modal/CompareModal.tsx
Labels: 🔨 fix

#133 feat: 프로필 페이지 모달 구현
  package.json
  src/app/@modal/(.)modal/profile/page.tsx
  src/app/@modal/(.)modal/profileEdit/page.tsx
  src/app/@modal/(.)modal/userFollowList/page.tsx
  src/app/modal/profile/page.tsx
  src/app/modal/profileEdit/page.tsx
  src/app/modal/userFollowList/page.tsx
  src/app/profile/page.tsx
  src/app/profile/queryKeyFactories.ts
  src/app/profile/queryOptions.ts
  src/components/@common/ProductCard.tsx
  src/components/Detail/ProductReviews/ReviewProfile.tsx
  src/components/Profile/ActivitySection/ActivityCard.tsx
  src/components/Profile/ActivitySection/ActivitySection.tsx
  src/components/Profile/ProductSection/MenuDropdown.tsx
  src/components/Profile/ProductSection/ProductList.tsx
  src/components/Profile/ProductSection/ProductSection.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/constants/productMenu.ts
  src/components/Profile/hooks/useFollowMutation.ts
  src/components/Profile/hooks/useProfileEditMutation.ts
  src/components/Profile/hooks/useUnFollowMutation.ts
  src/components/Profile/modal/EditModal.tsx
  src/components/Profile/modal/UserListModal.tsx
  src/components/Profile/skeleton/SkeletonUserListModal.tsx
  src/components/Profile/skeleton/index.ts
  src/components/Profile/types/followType.ts
  src/components/Profile/types/productType.ts
  src/components/Profile/types/profileTypes.ts
  src/components/Profile/types/userActivityType.ts
  src/shared/@common/apis/constants/API.ts
  src/shared/@common/apis/user.ts
  src/shared/@common/utils/formatCount.ts
  src/shared/@common/utils/getUserCookies.ts
  src/shared/@common/utils/index.ts
  src/shared/ui/Img/ImageComponent.tsx
  src/stores/index.ts
  src/stores/useUserInfoStore.ts
Labels: ⚙ api, 💄 ui

#160 refactor: alert 제거 후 방식 수정
  src/components/@common/modal/ProductModal.tsx
  src/components/Detail/modal/EditModal.tsx
  src/components/Detail/modal/ReviewModal.tsx
  src/shared/@common/utils/changeImage.ts
Labels: 🛠 refactor

#161 hot fix: env 파일 제거
  .env.production
  .github/workflows/BuildTest.yml
  .github/workflows/CICD.yml
  package.json
Labels: 🔥 hot fix!!

#164 fix: setErrorMessage 빠진 부분 추가
  src/components/Profile/modal/EditModal.tsx
Labels: 🔨 fix

#165 fix : 상품 리뷰, 편집 모달 disabled 속성 추가 및 캐시 설정
  src/components/Detail/ProductDetail/ProductDetail.tsx
  src/components/Detail/ProductDetail/hooks/useEditProductMutation.ts
  src/components/Detail/ProductReviews/ReviewProfile.tsx
  src/components/Detail/ProductReviews/hooks/useCreateReviewMutation.tsx
  src/components/Detail/modal/EditModal.tsx
  src/components/Detail/modal/ReviewModal.tsx
Labels: ✨ feature, 🔨 fix

#166 feat: Table 기능 추가
  src/app/@modal/(.)modal/compare/duplicateCompare/page.tsx
  src/app/modal/compare/duplicateCompare/page.tsx
  src/components/Compare/AutoComplete.tsx
  src/components/Compare/ComparingButton.tsx
  src/components/Compare/ComparisonResult.tsx
  src/components/Compare/Table.tsx
  src/components/Compare/types/productDetailType.ts
  src/shared/ui/Menu/Gnb/GnbHamburgerMenu.tsx
Labels: ✨ feature, 🔨 fix, 💄 ui

#168 feat: 구글 로그인 구현 및 localhost 부분 변경
  src/app/@modal/(.)modal/oauth/kakao/page.tsx
  src/app/modal/oauth/kakao/page.tsx
  src/app/oauth/google/page.tsx
  src/app/oauth/google/register/page.tsx
  src/app/oauth/kakao/page.tsx
  src/app/oauth/kakao/register/page.tsx
  src/components/Login/SocialLogin.tsx
  src/components/Oauth/SocialLoginForm.tsx
  src/components/Oauth/hooks/useSignInMutation.ts
Labels: ✨ feature, 🛠 refactor

#173 fix: redirectUri 수정
  src/components/Detail/ProductReviews/hooks/useCreateReviewMutation.ts
  src/components/Oauth/SocialLoginForm.tsx
Labels: 🔨 fix

#171 refactor: 상품 추가 모달 심화 및 기타 수정사항
  package.json
  public/loadingSpinnerCircle.gif
  src/app/@modal/(.)modal/home/productAdd/page.tsx
  src/app/modal/home/productAdd/page.tsx
  src/components/@common/modal/ProductModal.tsx
  src/components/@common/modal/index.ts
  src/components/Detail/modal/EditModal.tsx
  src/components/Home/RankingCard/RankingCard.tsx
  src/components/Home/hooks/GetCategoryOptions.ts
  src/components/Home/hooks/useProductAddMutation.ts
  src/components/Home/modal/AddModal.tsx
  src/components/Home/modal/LoadingSpinner.tsx
  src/components/Home/skeletons/SkeletonFilteredProducts.tsx
  src/components/Home/skeletons/SkeletonMainProducts.tsx
  src/shared/ui/Button/Floating/Floating.tsx
  src/shared/ui/Button/Floating/checkAccessToken.ts
  src/shared/ui/Button/Floating/index.ts
  yarn.lock
Labels: ✨ feature, ⚙ api, 🛠 refactor

#174 0.4.0 버전 업
  package.json
  public/loadingSpinnerCircle.gif
  src/app/@modal/(.)modal/home/productAdd/page.tsx
  src/app/modal/home/productAdd/page.tsx
  src/components/@common/modal/ProductModal.tsx
  src/components/@common/modal/index.ts
  src/components/Detail/ProductReviews/hooks/useCreateReviewMutation.ts
  src/components/Detail/modal/EditModal.tsx
  src/components/Home/RankingCard/RankingCard.tsx
  src/components/Home/hooks/GetCategoryOptions.ts
  src/components/Home/hooks/useProductAddMutation.ts
  src/components/Home/modal/AddModal.tsx
  src/components/Home/modal/LoadingSpinner.tsx
  src/components/Home/skeletons/SkeletonFilteredProducts.tsx
  src/components/Home/skeletons/SkeletonMainProducts.tsx
  src/components/Oauth/SocialLoginForm.tsx
  src/shared/ui/Button/Floating/Floating.tsx
  src/shared/ui/Button/Floating/checkAccessToken.ts
  src/shared/ui/Button/Floating/index.ts
  yarn.lock
Labels: ✨ feature

#177 design: 로고, favicon, 로딩 디자인 및 적용
  public/icon/newLoading.svg
  public/icon/newLogo.svg
  public/next.svg
  public/vercel.svg
  src/app/favicon.ico
  src/components/Detail/ProductDetail/ProductDetail.tsx
  src/components/Home/MainProducts/HotProducts/HotProducts.tsx
  src/components/Home/ReviewerRanking/ReviewerRanking.tsx
  src/shared/ui/Icon/Loading.tsx
  src/shared/ui/Icon/Logo.tsx
  svgr.d.ts
Labels: 🌈 enhancement

#178 fix: 상품 리스트 refetch 이슈 해결
  src/app/@modal/(.)modal/profile/loginAlert/page.tsx
  src/app/@modal/(.)modal/profile/profileEdit/page.tsx
  src/app/@modal/(.)modal/profile/userFollowList/page.tsx
  src/app/modal/profile/loginAlert/page.tsx
  src/app/modal/profile/profileEdit/page.tsx
  src/app/modal/profile/userFollowList/page.tsx
  src/app/profile/page.tsx
  src/app/profile/queryOptions.ts
  src/components/Detail/ProductDetail/hooks/useFavoriteMutation.ts
  src/components/Detail/ProductReviews/hooks/useCreateReviewMutation.ts
  src/components/Home/hooks/useProductAddMutation.ts
  src/components/Profile/ProductSection/ProductSection.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/modal/EditModal.tsx
  src/stores/useProfileStore.ts
Labels: 🔨 fix, 🛠 refactor

#180 feat: 비교하기 페이지 공유 버튼 구현
  src/components/Compare/ComparisonResult.tsx
  src/components/Compare/ShareIcon.tsx
Labels: ✨ feature

#181 fix: 공유 이미지 수정 및 버튼의 URL 수정
  src/components/Detail/ProductDetail/ShareButtons.tsx
Labels: 🔨 fix

#182 chore: console 삭제
  src/app/compare/queryOptions.ts
  src/components/@common/modal/CompareModal.tsx
  src/components/Compare/AutoComplete.tsx
  src/components/Compare/ComparingButton.tsx
  src/components/Compare/Table.tsx
  src/components/Compare/mock/PRODUCT_ID_1_MOCK.ts
  src/components/Compare/mock/PRODUCT_ID_2_MOCK.ts
  src/components/Compare/mock/PRODUCT_LIST_MOCK.ts
  src/components/Compare/mock/index.ts
  src/components/Home/hooks/GetCategoryOptions.ts
  src/components/Home/mock/CATEGORY_LIST_MOCK.ts
  src/components/Profile/ProductSection/MenuDropdown.tsx
  src/stores/index.ts
  src/stores/storeType.ts
  src/stores/useExampleStore.ts
Labels: 🔨 fix

#185 fix: 로그인 시 GnB의 검색바 위치 이동 수정 및 햄버거 메뉴 사용 후 자동 닫기 추가
  package.json
  src/shared/ui/Menu/Gnb/GnbHamburgerMenu.tsx
  src/shared/ui/Menu/Gnb/GnbSettingButton.tsx
  src/shared/ui/Menu/Gnb/GnbUser.tsx
  src/shared/ui/Menu/Gnb/types/gnbType.ts
  src/shared/ui/Menu/SideMenu/SideMenuTab.tsx
Labels: 🔨 fix

#186 0.6.0 버전 업
  package.json
  src/shared/ui/Menu/Gnb/GnbHamburgerMenu.tsx
  src/shared/ui/Menu/Gnb/GnbSettingButton.tsx
  src/shared/ui/Menu/Gnb/GnbUser.tsx
  src/shared/ui/Menu/Gnb/types/gnbType.ts
  src/shared/ui/Menu/SideMenu/SideMenuTab.tsx
Labels: ✨ feature

#187 fix: autoComplete=off 추가
  src/components/Detail/modal/EditModal.tsx
  src/components/Detail/modal/ReviewEditModal.tsx
  src/components/Detail/modal/ReviewModal.tsx
  src/components/Home/modal/AddModal.tsx
  src/components/Login/LoginForm.tsx
  src/components/Oauth/SocialLoginForm.tsx
  src/components/Profile/modal/EditModal.tsx
  src/components/Register/RegisterForm.tsx
  src/shared/ui/Menu/Gnb/GnbSearch.tsx
Labels: 🐞 bug

#188 feat: 프로젝트 전체 Redirect 설정
  package.json
  src/app/@modal/(.)modal/common/authAlert/page.tsx
  src/app/@modal/(.)modal/common/loginAlert/page.tsx
  src/app/@modal/(.)modal/detail/edit/page.tsx
  src/app/@modal/(.)modal/detail/review/page.tsx
  src/app/@modal/(.)modal/detail/reviewEdit/page.tsx
  src/app/@modal/(.)modal/home/productAdd/page.tsx
  src/app/@modal/(.)modal/profile/loginAlert/page.tsx
  src/app/@modal/(.)modal/profile/profileEdit/page.tsx
  src/app/@modal/(.)modal/profile/userFollowList/page.tsx
  src/app/[category]/[product]/page.tsx
  src/app/[category]/page.tsx
  src/app/modal/common/authAlert/page.tsx
  src/app/modal/common/loginAlert/page.tsx
  src/app/modal/detail/edit/page.tsx
  src/app/modal/detail/review/page.tsx
  src/app/modal/detail/reviewEdit/page.tsx
  src/app/modal/home/productAdd/page.tsx
  src/app/modal/profile/loginAlert/page.tsx
  src/app/modal/profile/profileEdit/page.tsx
  src/app/modal/profile/userFollowList/page.tsx
  src/app/profile/page.tsx
  src/components/Detail/ProductDetail/FavoriteButton.tsx
  src/components/Detail/ProductReviews/LikeButton.tsx
  src/components/Profile/ProfileCard.tsx
  src/middleware.ts
  src/shared/@common/constants/categories.ts
  src/shared/@common/constants/index.ts
Labels: ✨ feature

#189 1.0.0 정식 버전 업!
  package.json
  src/app/@modal/(.)modal/common/authAlert/page.tsx
  src/app/@modal/(.)modal/common/loginAlert/page.tsx
  src/app/@modal/(.)modal/detail/edit/page.tsx
  src/app/@modal/(.)modal/detail/review/page.tsx
  src/app/@modal/(.)modal/detail/reviewEdit/page.tsx
  src/app/@modal/(.)modal/home/productAdd/page.tsx
  src/app/@modal/(.)modal/profile/loginAlert/page.tsx
  src/app/@modal/(.)modal/profile/profileEdit/page.tsx
  src/app/@modal/(.)modal/profile/userFollowList/page.tsx
  src/app/[category]/[product]/page.tsx
  src/app/[category]/page.tsx
  src/app/modal/common/authAlert/page.tsx
  src/app/modal/common/loginAlert/page.tsx
  src/app/modal/detail/edit/page.tsx
  src/app/modal/detail/review/page.tsx
  src/app/modal/detail/reviewEdit/page.tsx
  src/app/modal/home/productAdd/page.tsx
  src/app/modal/profile/loginAlert/page.tsx
  src/app/modal/profile/profileEdit/page.tsx
  src/app/modal/profile/userFollowList/page.tsx
  src/app/profile/page.tsx
  src/components/Detail/ProductDetail/FavoriteButton.tsx
  src/components/Detail/ProductReviews/LikeButton.tsx
  src/components/Detail/modal/EditModal.tsx
  src/components/Detail/modal/ReviewEditModal.tsx
  src/components/Detail/modal/ReviewModal.tsx
  src/components/Home/modal/AddModal.tsx
  src/components/Login/LoginForm.tsx
  src/components/Oauth/SocialLoginForm.tsx
  src/components/Profile/ProfileCard.tsx
  src/components/Profile/modal/EditModal.tsx
  src/components/Register/RegisterForm.tsx
  src/middleware.ts
  src/shared/@common/constants/categories.ts
  src/shared/@common/constants/index.ts
  src/shared/ui/Menu/Gnb/GnbSearch.tsx
Labels: ✨ feature

#191 리드미 수정
  README.md
  package.json
Labels: 📄 docs
